language: scala

dist: trusty

scala:
  - 2.13.3
  - 2.12.11
  - 2.12.12

jdk:
  - openjdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt
    - $HOME/.cache

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

notifications:
  email:
    - r.janusz@avsystem.com
